Require OpenSSL 1.1.1 or newer
It's needed for the `-addext` param.

I think it's safe to do it now as 1.1.1 support ends soon:
Version 1.1.1 will be supported until 2023-09-11 (LTS).
https://www.openssl.org/policies/releasestrat.html

diff --git a/letsgetacert b/letsgetacert
--- a/letsgetacert
+++ b/letsgetacert
@@ -258,6 +258,13 @@ function callhook {
 	fi
 }
 
+OPENSSL_VERSION=$(openssl version)
+if echo $OPENSSL_VERSION | awk '$2 !~ /(^0\.)|(^1\.(0\.|1\.0))/ { exit 1 }'; then
+	echo "OpenSSL 1.1.1 or newer is required, yours is $OPENSSL_VERSION"
+	usage
+	exit 4
+fi
+
 parseopts $@
 loadconf
 processconf
